### ISSUE TITLE
채팅 기능 구현

### ISSUE THREAD

**Issue by cire0304** [masters2023-2nd-project-03/second-hand#107]
## ☑️ 진행할 작업

채팅 기능 구현
- 레디스 사용 x
- 기본적인 채팅
- 로그인 되지 않는 사용자도 가능

## 📝 TODO

- [ ] 채팅 관련 DTO 생성
- [ ] 채팅 컨트롤러 생성
- [ ] 채팅 서비스 생성
- [ ] 채팅 저장소 생성
