### ISSUE TITLE
물품 상세 페이지

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#110]
## ☑️ 진행할 작업

판매 중인 물품의 상세 페이지 UI를 구현합니다.

## 📝 TODO

- [x] : ItemDetail Page 컴포넌트 구현
- [x] : ItemDetail UI 구현
- [x] : ItemDetail Router 구현
