### ISSUE TITLE
DetailSliderPhotos 컴포넌트 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#111]
## 📝 TODO

- [x] : 기본 레이아웃 구현
- [ ] : 사진 슬라이더 적용
- [ ] : 사진 현재 페이지 아이콘 구현
