### ISSUE TITLE
채팅 페이지 UI 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#117]
## ☑️ 진행할 작업

실시간 채팅 페이지 UI를 구현합니다.

## 📝 TODO

- [x] : 페이지 컴포넌트
- [x] : 아이템 정보 컴포넌트
- [x] : 채팅 내용 컴포넌트
  - [x] : 상대방 대화 컴포넌트
  - [x] : 나의 대화 컴포넌트 
- [x] : 채팅 input 컴포넌트
