### ISSUE TITLE
로그인 정보 API에서 가져오기

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#123]
## ☑️ 진행할 작업

로그인 정보를 API에서 가져오는 연동 작업을 합니다.

## 📝 TODO

- [x] : 사용자 동네정보 가져오기
- [x] : 물품 상세 판매자 정보 가져오기
- [ ] : 채팅 페이지 판매자 정보 가져오기
- [ ] : 채팅 페이지 사용자 정보 입력하기
