### ISSUE TITLE
4주차까지 완성된 코드 정리

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#137]
## ☑️ 진행할 작업

4주차 까지 완성된 코드를 수정하고 정리합니다.

## 📝 TODO

- [x] : 커스텀훅 useAsync를 사용하지 않은 API 호출 코드를 수정합니다.
- [x] : 중복된 코드를 제거합니다.
- [x] : 필요없는 코드 & 주석 등을 제거합니다.
- [x] : 폴더 구조를 수정합니다.
