### ISSUE TITLE
동네 설정 페이지 제작

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#141]
## ☑️ 진행할 작업

[내 동네 설정하기] 버튼을 클리하면 동네 설정 페이지로 이동합니다.

## 📝 TODO

- [x] : 페이지 첫 화면은 이전에 선택된 동네 상태가 유지된다.
- [x] : 동네는 총 2개를 등록할 수 있다.
- [x] : 최소 1개 동네는 등록되어야 한다.
- [x] : 빈 동네를 선택하면 동네 리스트를 검색하는 페이지로 넘어간다.
