### ISSUE TITLE
동네 선택 리스트 페이지 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#142]
## ☑️ 진행할 작업

동네 리스트를 보여주고 선택하는 페이지를 구현합니다.

## 📝 TODO

- [x] : 전체 동네 리스트를 보여준다.
- [x] : 검색창을 이용하여 동네를 찾아준다.
- [x] : 동네를 선택하면 이전 [동네 설정] 페이지로 돌아가고 선택된 동네가 등록된다.
