### ISSUE TITLE
상품등록 : 가격을 제외한 모든 데이터는 필수가 되도록 한다.

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#163]
## ☑️ 진행할 작업

상품등록에서 필수 데이터가 입력 되어야만 등록이 되도록 구현

## 📝 TODO

- [x] : 동네 설정 기능 추가 (사용자 동네 정보 기반 연동)
- [x] : 필수 데이터가 모두 작성되어야 완료버튼이 활성화 된다.
- [x] : 가격은 필수데이터에서 제외 가능하다.
