### ISSUE TITLE
상품등록 : 사진 업로드 조건 부여

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#164]
## ☑️ 진행할 작업

사진 업로드 부분을 개선하고 조건을 만들어 준다.

## 📝 TODO

- [x] : 사진은 최소 1장, 최대 10장 조건을 추가한다.
- [x] : 10장이 넘는 사진 등록시 모달창으로 알림 구현 
- [x] : 첫 사진에는 [대표마크]를 표시한다.
