### ISSUE TITLE
상품등록 : 카테고리 기능 개선

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#165]
## ☑️ 진행할 작업

카테고리 추가 선택 기능을 추가한다.

## 📝 TODO

- [x] : 카테고리 리스트 페이지를 구현한다.
- [x] : 카테고리 추가 버튼을 누르면 전체 카테고리 리스트 페이지로 이동한다.
- [x] : 리스트 중 카테고리를 선택하면 상품등록 페이지로 돌아가며 선택된 카테고리가 적용되도록 한다.
