### ISSUE TITLE
상품등록 : 동네 설정 기능 추가

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#166]
## ☑️ 진행할 작업

상품등록시 사용자 동네 리스트중 하나를 선택할 수 있도록 구현한다.

## 📝 TODO

- [x] : 처음에는 메인 동네가 설정되도록 한다.
- [x] : 내가 등록한 동네 중 선택이 가능하도록 한다.
- [x] : 선택된 동네가 나의 메인 동네가 되도록 한다.
