### ISSUE TITLE
상품상세 (판매자) - 상세 페이지 UI 개선

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#173]
## ☑️ 진행할 작업

상품 상세 페이지의 기본적인 UI를 개선합니다.

## 📝 TODO

- [x] : 판매자 정보 추가
- [x] : 상품 상태 (판매중, 예약중, 판매완료) 버튼 추가
- [x] : 채팅, 관심, 조회수 정보 추가
- [x] : 하단 탭바 다지인 개선
