### ISSUE TITLE
상품상세 (판매자) - 하단 탭바 기능 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#175]
## ☑️ 진행할 작업

상품상세 페이지 하단 탭의 기능을 구현합니다.

## 📝 TODO

- [x]  관심 버튼, 채팅하기 버튼을 배치한다.
- [x]  관심 버튼을 클릭하면 색이 칠해지고 해당 상품을 관심 등록한다.
- [x]  가격이 없다면 “가격 미정”으로 표시한다.
- [x]  대화중인 채팅방 버튼에는 존재하는 채팅방수 표시
  - [x]  해당 버튼을 누르면 채팅방 리스트 화면으로 이동한다.
  - [x]  채팅한 내역이 없는 경우 채팅방수는 표시 되지 않고 클릭시 채팅한 이웃이 없다고 알려준다.
