### ISSUE TITLE
상품상세 (판매자) - 상품 이미지 슬라이더 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#176]
## ☑️ 진행할 작업

등록된 사진들이 슬라이더로 보이도록 구현합니다.

## 📝 TODO

- [x]  이미지 하단에 등록된 이미지가 몇장이며, 지금 몇 번째 이미지를 보는지 알려주는 네비를 추가한다.
    - [x]  네비가 잘 보이도록 이미지에는 검정색 그라데이션을 넣는다.
    - [x]  좌우 버튼으로 이미지를 넘긴다.
