### ISSUE TITLE
상품상세 (구매자) - 다른 사람이 등록한 물품의 상세 페이지

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#188]
## ☑️ 진행할 작업

다른 사람의 판매 상품 상세 페이지를 구성한다.

## 📝 TODO

- [x] : 상품 정보를 수정하거나 삭제하는 더보기 버튼을 비활성화 한다.
- [x] : 상품의 상태를 수정하는 버튼을 비활성화 한다.
- [x] : 채팅하기 버튼을 누르면 채팅을 시작하거나 채팅중인 페이지로 넘어간다.
