### ISSUE TITLE
판매 내역 - 페이지 UI 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#190]
## ☑️ 진행할 작업

판매 내역 페이지의 UI를 구현한다.

## 📝 TODO

- [x] : 상단에 판매 상태를 선택하는 버튼 컴포넌트 구현
- [x] : 해당 상품이 보여진다
- [x] : 해당 상품을 클릭하면 상세 페이지로 이동한다
