### ISSUE TITLE
판매 내역 - 판매 내역 상품의 정보를 수정하는 기능 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#191]
## ☑️ 진행할 작업

판매 내역에서 확인되는 상품의 [더 보기] 버튼 클릭시 수정할 수 있는 기능을 구현한다.

## 📝 TODO

- [x] : [더 보기] 버튼을 누르면 수정 항목 리스트를 모달로 보여준다.
- [x] : 현재 상품 상태에 따라 상태 전환 버튼이 다르게 나오도록 보여준다.
- [x] : 상품의 상태 변경, 삭제 기능이 추가된다.
