### ISSUE TITLE
채팅 - 채팅방 UI/UX 수정 

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#206]
## ☑️ 진행할 작업

채팅방의 UI/UX를 수정합니다.

## 📝 TODO

- [x] : 상대방 닉네임 가져오기
- [x] : 한글 채팅시 입력값이 두번 일어나는 버그 해결하기
- [x] : 채팅방 나가기 추가
