### ISSUE TITLE
회원가입 UI 구현

### ISSUE THREAD

**Issue by noah0316** [masters2023-2nd-project-03/second-hand#44]
## ☑️ 진행할 작업

- 회원가입을 하기 위해 필요한 UI를 구현합니다.

## 📝 TODO

- [x] ID를 입력하기 위해 필요한 UI 구현
- [x] 프로필 이미지를 표시할 UI 구현
- [x] 위치를 추가하는 화면으로 넘어가기 위해 필요한 UI 구현
- [x] 화면을 닫거나, 완료하기 위해 필요한 UI 구현

## ⚙️ 기타

- 피그마 참고
