### ISSUE TITLE
내 계정 UI 구현

### ISSUE THREAD

**Issue by Aiden0704** [masters2023-2nd-project-03/second-hand#45]
## ☑️ 진행할 작업

- 로그인을 하기위해 필요한 UI를 구현합니다

## 📝 TODO

- [ ] 로그인을 하기 위한 UI 구현
- [x] 회원가입 화면으로 넘어가기 위한 UI 구현
- [x] 아이디를 입력하기 위한 UI 구현

## ⚙️ 기타

- 피그마 참고
