### ISSUE TITLE
tapBar route 구현

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#50]
## ☑️ 진행할 작업

tapBar에 route 기능을 구현합니다.

## 📝 TODO

- [x] : 홈화면, 판매내역, 관심목록, 채팅, 내 계정 임시 페이지 컴포넌트를 생성한다.
- [x] : tapBar의 아이콘을 클릭하면 해당 페이지로 이동한다.
- [x] : 현재 선택된 페이지의 아이콘은 두껍게 표현한다.
