### ISSUE TITLE
중고거래 물품을 불러온다.

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#54]
## ☑️ 진행할 작업

홈 화면에서 보여지는 중고거래 상품을 불러옵니다.

## 📝 TODO

- [x] : 중고거래 물품을 보여주는 컴포넌트를 구현한다.
- [ ] : 중고거래 물품을 10개 단위로 불러온다. -> API 나오면 구현
- [ ] : 무한 스크롤을 구현하여 스크롤시 10개 단위로 추가 되도록 구현한다. -> API 나오면 구현

## ⚙️ 기타

- [x] : 상품 제목은 최대 2줄까지 표시한다. 2줄이 넘을 경우 ...으로 표시한다.
- [x] : 제목이 두 줄일때는 설명 부분이 밑으로 내려간다.
