### ISSUE TITLE
내 물건 팔기 페이지

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#76]
## ☑️ 진행할 작업

내 물건 팔기 페이지 UI를 구현합니다.

## 📝 TODO

- [x] : 페이지 레이아웃
- [x] : 하단 탭 컴포넌트 생성
  - [x] : 동네설정 
- [x] : 물건 사진 등록 컴포넌트 생성
  - [x] : 컴포넌트 UI 
  - [x] : 이미지 첨부 이벤트
  - [x] : 이미지 첨부 수량 상태 관리
  - [x] : 이미지 삭제 이벤트
  - [x] : 이미지 삭제 후 첨부 수량 상태 업데이트
- [x] : 메인 내용 구성
  - [x] : 타이틀
  - [x] : 가격
  - [x] : 내용
