### ISSUE TITLE
이미지 등록 컴포넌트 생성

### ISSUE THREAD

**Issue by sarangdaddy** [masters2023-2nd-project-03/second-hand#79]
## ☑️ 진행할 작업

내 물건 판매에서 이미지를 등록하는 컴포넌트를 구현합니다.

## 📝 TODO

- [x] : 컴포넌트 UI 
- [ ] : 이미지 첨부 이벤트
- [ ] : 이미지 첨부 수량 상태 관리
- [ ] : 이미지 삭제 이벤트
- [ ] : 이미지 삭제 후 첨부 수량 상태 업데이트
